### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by zxx01** [jzyustc/MBRS#10]
save_images(saved_all, epoch, result_folder + "images/", resize_to=(W, H))  in train.py may occur error! since the param "saved_all" can be NONE !

**Comment by zxx01** [comment]
saved_iterations = np.random.choice(
        np.arange(len(val_dataset)), size=save_images_number, replace=False);

for i, images in enumerate(val_dataloader):

if i in saved_iterations:
            if saved_all is None:
                saved_all = get_random_images(
                    image, encoded_images, noised_images)
            else:
                saved_all = concatenate_images(
                    saved_all, image, encoded_images, noised_images)

saved_iterations is from len(val_dataset), which is much bigger than len(val_dataloader)!!!!

**Comment by jzyustc** [comment]
Thanks for your report of this bug. I am currently working with another projects, so I may fix it later when I am free.

**Comment by jzyustc** [comment]
If this bug occurs, I advise you to solve it by: 

1. change `np.arange(len(val_dataset))` to `np.arange(len(val_dataloader))` in 
https://github.com/jzyustc/MBRS/blob/c0f31767bfe4262ea633c5779dacda6264795f7a/train.py#L91

2. change the batch size in validation dataloader to 1 in
https://github.com/jzyustc/MBRS/blob/c0f31767bfe4262ea633c5779dacda6264795f7a/train.py#L19

I do not try them, but I think they should work.

**Comment by zxx01** [comment]
Thanks for your reply! I have solved this bug by change `np.arange(len(val_dataset))` to `np.arange(len(val_dataloader))`.

**Comment by jzyustc** [comment]
Bug fixed. Closed.
