### ISSUE TITLE
unpack error

### ISSUE THREAD

**Issue by jinganglang567** [jzyustc/MBRS#12]
hi sorry to bother you i meet the problem ,can yo help me?

original_images, watermarked_images, noised_images = saved_all
TypeError: cannot unpack non-iterable NoneType object

**Comment by jzyustc** [comment]
Hi, pls refer to https://github.com/jzyustc/MBRS/issues/10#issuecomment-1883040524 for solution. I will fix this bug later when I am free.

**Comment by jinganglang567** [comment]
sorry sir it didn't work and it raise new error
File "/root/autodl-tmp/MBRS-main/utils/save_images.py", line 26, in save_images
    noised_images = (noised_images + 1) / 2
TypeError: can only concatenate list (not "int") to list
