### ISSUE TITLE
decode the message

### ISSUE THREAD

**Issue by jinganglang567** [jzyustc/MBRS#13]
sir,sorry to bother you ,if i want to know the message the model embed,what should i do

**Comment by jzyustc** [comment]
If you want to decode the watermark from an watermarked image, you can refer to the `./test.py` for details. The below code can extract watermark from `noised_images`

https://github.com/jzyustc/MBRS/blob/c0f31767bfe4262ea633c5779dacda6264795f7a/test.py#L52

**Comment by jinganglang567** [comment]
thank you doctor
