### ISSUE TITLE
The extraction of watermarks has a high error rate

### ISSUE THREAD

**Issue by python-pop** [jzyustc/MBRS#14]
Hello, thanks for the code, but I'm having a problem. 
For a photo that has been watermarked with your model, I save the watermark in advance, and then put the image into the decoder to extract, I tested a hundred photos, but the error rate of each is 0.4~0.5,and I also set only_decoder=True,is it a problem with my code？
![image](https://github.com/jzyustc/MBRS/assets/54395315/05039021-f518-4dab-81d8-1e4a10a89cbd)
![image](https://github.com/jzyustc/MBRS/assets/54395315/06de2742-1b69-4cf5-8d1b-51891e63722c)

**Comment by jzyustc** [comment]
Hi, there may be many reasons for decoding error, and I am not sure about what happens to you.

You can try to use the released test code to test on your original photos. Make sure the resolution of images and watermark length are correct. 
- If it works, the issue might be with your code for saving or loading photos or messages. For example, inconsistencies in the saving and loading processes could be the problem, and introducing unexpected disruptions (for example, screen shooting) also causes this issue.
- If using the official test code also fails, the issues might be with the generalization ability of the model. In fact, we did not try it on other personal datasets for evaluation.

**Comment by python-pop** [comment]
Thank you for your reply.
 I've tested with the official code and the error rate is 0, so for an image that has been watermarked, this code is fine if only the watermark is extracted, right?
If so, I'm going to check the preservation of the photo.I have verified that there is no problem with the saving and loading of the original message.

**Comment by python-pop** [comment]
Hello, I saved the watermarked photo the same way you saved the image, and made sure that the pixel value of the saved and loaded ones is the same, but the error rate of extracting the watermark is still very high. Have you tried saving the photos before extracting them?

**Comment by jzyustc** [comment]
If this works well for your data, I think there should be not problem with our codes / models, and you can check what is the difference between your code and the JpegTest.

**Comment by python-pop** [comment]
Thank you, I found that the problem appeared on the Dataset, I rewrote a Dataset, and now the problem has been solved.
