### ISSUE TITLE
SSIM

### ISSUE THREAD

**Issue by JusticeByLu** [jzyustc/MBRS#17]
Hello author! Thank you very much for providing the project code. When I encountered the following problem while running the code, I would like to ask how to solve it?

D:\Anaconda\Anaconda\envs\MBRS\python.exe D:\PyCharm_workspace\copyrightprotection\MBRS-main\train.py 
-----------------------Date: 2024/08/06 11:28:26-----------------------
project_name = MBRS
with_diffusion = False
only_decoder = False
epoch_number = 101
batch_size = 4
train_continue = False
train_continue_path = /
train_continue_epoch = 0
dataset_path = datasets/
save_images_number = 4
H = 128
W = 128
message_length = 64
lr = 0.001
noise_layers = ['Combined([JpegMask(50),Jpeg(50),Identity()])']

0.001

Start training : 

Traceback (most recent call last):
  File "D:\PyCharm_workspace\copyrightprotection\MBRS-main\train.py", line 54, in <module>
    result = network.train(image, message) if not only_decoder else network.train_only_decoder(image, message)
  File "D:\PyCharm_workspace\copyrightprotection\MBRS-main\network\Network.py", line 99, in train
    ssim = 1 - 2 * kornia.losses.ssim(encoded_images.detach(), images, window_size=5, reduction="mean")
TypeError: 'module' object is not callable

**Comment by jzyustc** [comment]
Hi, I guess this is due to an incorrect version of kornia. To use the original code, kornia==0.3.0 works. You can also change the code to match a later version of kornia.

**Comment by JusticeByLu** [comment]
> Hi, I guess this is due to an incorrect version of kornia. To use the original code, kornia==0.3.0 works. You can also change the code to match a later version of kornia.

Thank you for your response! Perhaps this is the reason why the code cannot run, as the configuration mentioned in the Requirements file is already an outdated version. I find it difficult to download the same version now.

**Comment by jzyustc** [comment]
Since kornia is used only in a few lines (e.g., calculation of ssim, median blur, and gaussian blur), I think it will not be difficult to adapt these lines to higher versions of kornia.

**Comment by JusticeByLu** [comment]
> Since kornia is used only in a few lines (e.g., calculation of ssim, median blur, and gaussian blur), I think it will not be difficult to adapt these lines to higher versions of kornia.

The problem has been resolved. Thank you very much for your help!

**Comment by PZ04111618** [comment]
> > Since kornia is used only in a few lines (e.g., calculation of ssim, median blur, and gaussian blur), I think it will not be difficult to adapt these lines to higher versions of kornia.
> 
> The problem has been resolved. Thank you very much for your help!

Hi，Can I use ssim_loss replace of the ssim, for example:
![image](https://github.com/user-attachments/assets/b6f09e8b-b51f-4c1b-8f61-185a5ffdb211)
![image](https://github.com/user-attachments/assets/5f9e9ba8-73ad-4780-87ad-e15a4a6895f0)
Thanks for your answer！

**Comment by PZ04111618** [comment]
> > > Since kornia is used only in a few lines (e.g., calculation of ssim, median blur, and gaussian blur), I think it will not be difficult to adapt these lines to higher versions of kornia.
> > 
> > 
> > The problem has been resolved. Thank you very much for your help!
> 
> Hi，Can I use ssim_loss replace of the ssim, for example: ![image](https://private-user-images.githubusercontent.com/69287130/389352157-b6f09e8b-b51f-4c1b-8f61-185a5ffdb211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDQ0NDksIm5iZiI6MTczMjUwNDE0OSwicGF0aCI6Ii82OTI4NzEzMC8zODkzNTIxNTctYjZmMDllOGItYjUxZi00YzFiLThmNjEtMTg1YTVmZmRiMjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAzMDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDI2NjE1MTkyY2NlZWJlMWQxZmE3ZTdmMTc2YzhhNGU4YTI1ZDRlOTI5MDgwN2QyZTgxNmE0MTdjNTg0NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iGE7VADzA5wXkN4RB1-5VgOJMmUGLOxWgnMCKVRvilY) ![image](https://private-user-images.githubusercontent.com/69287130/389352181-5f9e9ba8-73ad-4780-87ad-e15a4a6895f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDQ0NDksIm5iZiI6MTczMjUwNDE0OSwicGF0aCI6Ii82OTI4NzEzMC8zODkzNTIxODEtNWY5ZTliYTgtNzNhZC00NzgwLTg3YWQtZTE1YTRhNjg5NWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAzMDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZjYxNTc1YzA2ZDViNzk2NGViNzg0NWEzODZjNTE2ZDcwMmFiZWI0MDhiZTM4OTViNDUxMTRmNGFhMTE5ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6sT0Y-U_yxG-WUHnjqpVaKR-FT5MjDhVF0hWqmJG3ls) Thanks for your answer！
